"""Deterministic earnings fixtures — never labelled live."""

from __future__ import annotations

from datetime import date, timedelta
from typing import Any

from app.market_intelligence.earnings.types import (
    ContractCandidate,
    EarningsEvent,
    EarningsPhase,
)


def _d(days: int) -> date:
    return date.today() + timedelta(days=days)


FIXTURE_EVENTS: list[EarningsEvent] = [
    EarningsEvent(
        symbol="AAPL",
        company_name="Apple Inc.",
        report_date=_d(5),
        release_time="AMC",
        phase=EarningsPhase.PRE_EARNINGS,
        eps_estimate=1.65,
        revenue_estimate=94_500_000_000,
        guidance_note="Street expects steady Services growth; hardware mixed.",
        analyst_sentiment="mixed",
        sector="Technology",
        sector_direction="constructive",
        market_direction="cautiously_bullish",
        price=210.0,
        volume=52_000_000,
        support=202.0,
        resistance=218.0,
        historical_moves_pct=[6.2, 9.1, 5.4, 11.0],
        data_status="simulated",
        data_source="earnings_fixture",
        missing_fields=[],
    ),
    EarningsEvent(
        symbol="NVDA",
        company_name="NVIDIA Corp.",
        report_date=_d(2),
        release_time="AMC",
        phase=EarningsPhase.PRE_EARNINGS,
        eps_estimate=0.88,
        revenue_estimate=46_000_000_000,
        guidance_note="Elevated bar; guidance risk is the main uncertainty.",
        analyst_sentiment="bullish",
        sector="Technology",
        sector_direction="leading",
        market_direction="cautiously_bullish",
        price=120.0,
        volume=180_000_000,
        support=112.0,
        resistance=128.0,
        historical_moves_pct=[12.0, 8.5, 15.2, 9.8],
        data_status="simulated",
        data_source="earnings_fixture",
        missing_fields=[],
    ),
    EarningsEvent(
        symbol="XOM",
        company_name="Exxon Mobil",
        report_date=_d(1),
        release_time="BMO",
        phase=EarningsPhase.WAITING_FOR_REPORT,
        eps_estimate=1.72,
        revenue_estimate=82_000_000_000,
        guidance_note=None,
        analyst_sentiment="unknown",
        sector="Energy",
        sector_direction="mixed",
        market_direction="cautiously_bullish",
        price=112.0,
        volume=18_000_000,
        support=108.0,
        resistance=116.0,
        historical_moves_pct=[3.1, 2.4, 4.0, 2.8],
        data_status="simulated",
        data_source="earnings_fixture",
        missing_fields=["guidance_note", "analyst_sentiment"],
    ),
    EarningsEvent(
        symbol="COST",
        company_name="Costco Wholesale",
        report_date=_d(-1),
        release_time="AMC",
        phase=EarningsPhase.POST_RELEASE_UNCONFIRMED,
        eps_estimate=4.22,
        revenue_estimate=62_000_000_000,
        eps_actual=4.35,
        revenue_actual=63_200_000_000,
        guidance_note="Beat; membership trends solid — open confirmation pending.",
        analyst_sentiment="bullish",
        sector="Consumer",
        sector_direction="strengthening",
        market_direction="cautiously_bullish",
        price=890.0,
        volume=4_200_000,
        support=870.0,
        resistance=910.0,
        historical_moves_pct=[4.5, 3.8, 5.1, 4.0],
        data_status="simulated",
        data_source="earnings_fixture",
        missing_fields=[],
    ),
    EarningsEvent(
        symbol="WEAK",
        company_name="Weak Liquidity Co",
        report_date=_d(4),
        release_time="AMC",
        phase=EarningsPhase.PRE_EARNINGS,
        eps_estimate=0.40,
        revenue_estimate=1_200_000_000,
        guidance_note=None,
        analyst_sentiment="unknown",
        sector="Other",
        sector_direction="unknown",
        market_direction="unknown",
        price=25.0,
        volume=900_000,
        support=23.0,
        resistance=27.0,
        historical_moves_pct=[5.0, 6.0, 4.5, 5.5],
        data_status="simulated",
        data_source="earnings_fixture",
        missing_fields=["guidance_note", "analyst_sentiment", "sector_direction"],
        stale=False,
    ),
    EarningsEvent(
        symbol="STALE",
        company_name="Stale Data Inc",
        report_date=_d(3),
        release_time="unknown",
        phase=EarningsPhase.PRE_EARNINGS,
        eps_estimate=None,
        revenue_estimate=None,
        price=50.0,
        historical_moves_pct=[],
        data_status="partial",
        data_source="earnings_fixture",
        missing_fields=[
            "eps_estimate",
            "revenue_estimate",
            "historical_moves",
            "options_chain",
            "iv",
        ],
        stale=True,
    ),
]


# Contract packs keyed by symbol for engine tests / fixture desk
FIXTURE_CHAINS: dict[str, dict[str, Any]] = {
    "AAPL": {
        "atm_iv": 0.32,
        "straddle_call_mid": 7.8,
        "straddle_put_mid": 7.6,
        "historical_iv_crush": 31.0,
        "contracts": [
            ContractCandidate(
                option_type="call",
                strike=215.0,
                expiration=(_d(12)).isoformat(),
                premium=3.45,
                bid=3.35,
                ask=3.55,
                volume=4200,
                open_interest=1800,
                iv=0.34,
                delta=0.38,
                moneyness="otm",
                spread_pct=5.8,
            ),
            ContractCandidate(
                option_type="call",
                strike=210.0,
                expiration=(_d(12)).isoformat(),
                premium=7.20,
                bid=7.05,
                ask=7.35,
                volume=5100,
                open_interest=3200,
                iv=0.32,
                delta=0.52,
                moneyness="atm",
                spread_pct=4.2,
            ),
        ],
    },
    "NVDA": {
        "atm_iv": 0.55,
        "straddle_call_mid": 8.5,
        "straddle_put_mid": 8.2,
        "historical_iv_crush": 36.0,
        "contracts": [
            ContractCandidate(
                option_type="call",
                strike=128.0,
                expiration=(_d(9)).isoformat(),
                premium=2.10,
                bid=2.00,
                ask=2.20,
                volume=8800,
                open_interest=4500,
                iv=0.58,
                delta=0.32,
                moneyness="otm",
                spread_pct=9.5,
            ),
            ContractCandidate(
                option_type="call",
                strike=120.0,
                expiration=(_d(9)).isoformat(),
                premium=6.40,
                bid=6.25,
                ask=6.55,
                volume=12000,
                open_interest=8000,
                iv=0.55,
                delta=0.51,
                moneyness="atm",
                spread_pct=4.7,
            ),
        ],
    },
    "WEAK": {
        "atm_iv": 0.40,
        "straddle_call_mid": 1.1,
        "straddle_put_mid": 1.0,
        "historical_iv_crush": 28.0,
        "contracts": [
            ContractCandidate(
                option_type="call",
                strike=28.0,
                expiration=(_d(10)).isoformat(),
                premium=0.35,
                bid=0.20,
                ask=0.50,
                volume=40,
                open_interest=80,
                iv=0.55,
                delta=0.22,
                moneyness="otm",
                spread_pct=85.0,
            ),
        ],
    },
    "COST": {
        "atm_iv": 0.22,
        "straddle_call_mid": 18.0,
        "straddle_put_mid": 17.0,
        "historical_iv_crush": 24.0,
        "contracts": [
            ContractCandidate(
                option_type="call",
                strike=900.0,
                expiration=(_d(8)).isoformat(),
                premium=14.0,
                bid=13.6,
                ask=14.4,
                volume=2100,
                open_interest=1600,
                iv=0.24,
                delta=0.45,
                moneyness="otm",
                spread_pct=5.7,
            ),
        ],
    },
    "XOM": {
        "atm_iv": 0.24,
        "straddle_call_mid": 2.4,
        "straddle_put_mid": 2.3,
        "historical_iv_crush": 22.0,
        "contracts": [
            ContractCandidate(
                option_type="call",
                strike=114.0,
                expiration=(_d(7)).isoformat(),
                premium=1.85,
                bid=1.75,
                ask=1.95,
                volume=1500,
                open_interest=2200,
                iv=0.25,
                delta=0.40,
                moneyness="otm",
                spread_pct=10.8,
            ),
        ],
    },
}


def fixture_watchlist() -> list[dict[str, Any]]:
    return [
        {"symbol": e.symbol, "report_date": e.report_date.isoformat(), "phase": e.phase.value, "note": "Active earnings watch"}
        for e in FIXTURE_EVENTS
        if e.phase != EarningsPhase.EXPIRED
    ]
